import Head from "next/head";
import Signup from "../components/Signup.js";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Creative Platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Signup />
    </div>
  );
}
